pipeline {
    agent any 

    tools {
        nodejs "node"
    }

    stages {
        stage('Cypress Parallel Test Suite'){
            parallel {
                stage('Slave Node 1'){
                    agent {
                        label "remote_node1"
                    } 
                    steps {
                        git url: 'https://github.com/syzzana/learning-cypress-project.git'
                        bat 'npm install'
                        bat 'npm update' 
                        bat 'npm run  triggerAllTests-autostore-dashboard'
                    }
                }
            }
        }
         stage('Slave Node 2'){
                    agent {
                        label "remote_node2"
                    } 
                    steps {
                        git url: 'https://github.com/syzzana/learning-cypress-project.git'
                        bat 'npm install'
                        bat 'npm update' 
                        bat 'npm run  triggerAllTests-autostore-dashboard'
                    }
                }
    }
}